{
  "openapi": "3.0.0",
  "info": {
    "title": "SPURESTAPI",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/OrganizationUnits/GetAllOrganizationUnits": {
      "get": {
        "summary": "GetAllOrganizationUnits",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "OrganizationUnitName": {
                        "type": "string"
                      },
                      "OrganizationUnitType": {
                        "type": "string"
                      },
                      "OrganizationUnitCode": {
                        "type": "string"
                      },
                      "OrganizationUnitParentCode": {
                        "type": "string"
                      },
                      "OrganizationUnitShortCut": {
                        "type": "string"
                      },
                      "OrganizationUnitDirector": {
                        "type": "string"
                      },
                      "OrganizationUnitDeputyDirector": {
                        "type": "string"
                      },
                      "OrganizationUnitNetworkAdministrator": {
                        "type": "string"
                      },
                      "OrganizationUnitNetworkDeputyAdministrator": {
                        "type": "string"
                      },
                      "OrganizationUnitMembers": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "OrganizationUnitSponsors": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "OrganizationUnitAssistants": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "OrganizationUnitTelephone1": {
                        "type": "string"
                      },
                      "OrganizationUnitTelephone2": {
                        "type": "string"
                      },
                      "OrganizationUnitEmail": {
                        "type": "string"
                      },
                      "OrganizationUnitAddressStreet": {
                        "type": "string"
                      },
                      "OrganizationUnitAddressStreetNumber": {
                        "type": "string"
                      },
                      "OrganizationUnitAddressCity": {
                        "type": "string"
                      },
                      "OrganizationUnitAddressPSC": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "OrganizationUnitName": "Úsek ústředního ředitele",
                        "OrganizationUnitType": "0c",
                        "OrganizationUnitCode": "100000",
                        "OrganizationUnitParentCode": "000001",
                        "OrganizationUnitShortCut": "UUR",
                        "OrganizationUnitDirector": "jana.krejci@spu.cz",
                        "OrganizationUnitDeputyDirector": "jana.krejci@spu.cz",
                        "OrganizationUnitNetworkAdministrator": "jana.krejci@spu.cz",
                        "OrganizationUnitNetworkDeputyAdministrator": "jana.krejci@spu.cz",
                        "OrganizationUnitMembers": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitSponsors": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitAssistants": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitTelephone1": "777 777 777",
                        "OrganizationUnitTelephone2": "999 999 999",
                        "OrganizationUnitEmail": "info@spu.cz",
                        "OrganizationUnitAddressStreet": "Husinecka",
                        "OrganizationUnitAddressStreetNumber": "1024/11a",
                        "OrganizationUnitAddressCity": "Praha 3",
                        "OrganizationUnitAddressPSC": "13000"
                      },
                      {
                        "OrganizationUnitName": "Úsek ústředního ředitele",
                        "OrganizationUnitType": "0c",
                        "OrganizationUnitCode": "100000",
                        "OrganizationUnitParentCode": "000001",
                        "OrganizationUnitShortCut": "UUR",
                        "OrganizationUnitDirector": "jana.krejci@spu.cz",
                        "OrganizationUnitDeputyDirector": "jana.krejci@spu.cz",
                        "OrganizationUnitNetworkAdministrator": "jana.krejci@spu.cz",
                        "OrganizationUnitNetworkDeputyAdministrator": "jana.krejci@spu.cz",
                        "OrganizationUnitMembers": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitSponsors": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitAssistants": [
                          "jana.krejci@spu.cz",
                          "martin.cuchran@spu.cz"
                        ],
                        "OrganizationUnitTelephone1": "777 777 777",
                        "OrganizationUnitTelephone2": "999 999 999",
                        "OrganizationUnitEmail": "info@spu.cz",
                        "OrganizationUnitAddressStreet": "Husinecka",
                        "OrganizationUnitAddressStreetNumber": "1024/11a",
                        "OrganizationUnitAddressCity": "Praha 3",
                        "OrganizationUnitAddressPSC": "13000"
                      }
                    ]
                  }
                }
              }
            }
          },
          "": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "OrganizationUnitName": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {}
                }
              }
            }
          }
        },
        "operationId": "get-OrganizationUnits-GetAllOrganizationUnits",
        "description": "Returns all organization units"
      }
    },
    "/OrganizationUnits/GetOrganizationUnitByCode/{OrganizationUnitCode}": {
      "get": {
        "summary": "GetOrganizationUnitByCode",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "OrganizationUnitName": {
                      "type": "string"
                    },
                    "OrganizationUnitType": {
                      "type": "string"
                    },
                    "OrganizationUnitCode": {
                      "type": "string"
                    },
                    "OrganizationUnitParentCode": {
                      "type": "string"
                    },
                    "OrganizationUnitShortCut": {
                      "type": "string"
                    },
                    "OrganizationUnitDirector": {
                      "type": "string"
                    },
                    "OrganizationUnitDeputyDirector": {
                      "type": "string"
                    },
                    "OrganizationUnitNetworkAdministrator": {
                      "type": "string"
                    },
                    "OrganizationUnitNetworkDeputyAdministrator": {
                      "type": "string"
                    },
                    "OrganizationUnitMembers": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "OrganizationUnitSponsors": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "OrganizationUnitAssistants": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "OrganizationUnitTelephone1": {
                      "type": "string"
                    },
                    "OrganizationUnitTelephone2": {
                      "type": "string"
                    },
                    "OrganizationUnitEmail": {
                      "type": "string"
                    },
                    "OrganizationUnitAddressStreet": {
                      "type": "string"
                    },
                    "OrganizationUnitAddressStreetNumber": {
                      "type": "string"
                    },
                    "OrganizationUnitAddressCity": {
                      "type": "string"
                    },
                    "OrganizationUnitAddressPSC": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "OrganizationUnitName": "Úsek ústředního ředitele",
                      "OrganizationUnitType": "0c",
                      "OrganizationUnitCode": "100000",
                      "OrganizationUnitParentCode": "000001",
                      "OrganizationUnitShortCut": "UUR",
                      "OrganizationUnitDirector": "jana.krejci@spu.cz",
                      "OrganizationUnitDeputyDirector": "jana.krejci@spu.cz",
                      "OrganizationUnitNetworkAdministrator": "jana.krejci@spu.cz",
                      "OrganizationUnitNetworkDeputyAdministrator": "jana.krejci@spu.cz",
                      "OrganizationUnitMembers": [
                        "jana.krejci@spu.cz",
                        "martin.cuchran@spu.cz"
                      ],
                      "OrganizationUnitSponsors": [
                        "jana.krejci@spu.cz",
                        "martin.cuchran@spu.cz"
                      ],
                      "OrganizationUnitAssistants": [
                        "jana.krejci@spu.cz",
                        "martin.cuchran@spu.cz"
                      ],
                      "OrganizationUnitTelephone1": "777 777 777",
                      "OrganizationUnitTelephone2": "999 999 999",
                      "OrganizationUnitEmail": "info@spu.cz",
                      "OrganizationUnitAddressStreet": "Husinecka",
                      "OrganizationUnitAddressStreetNumber": "1024/11a",
                      "OrganizationUnitAddressCity": "Praha 3",
                      "OrganizationUnitAddressPSC": "13000"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-OrganizationUnits-GetOrganizationUnitByCode",
        "parameters": [],
        "description": "Return organization unit by defined organization unit code"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "OrganizationUnitCode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/OrganizationUnits/SetOrganizationUnitByCode/{OrganizationUnitCode}": {
      "post": {
        "summary": "SetOrganizationUnitByCode",
        "operationId": "post-OrganizationUnits-SetOrganizationUnitByCode",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "OrganizationUnitAddressPSC": {
                    "type": "string"
                  },
                  "OrganizationUnitAddressCity": {
                    "type": "string"
                  },
                  "OrganizationUnitAddressStreetNumber": {
                    "type": "string"
                  },
                  "OrganizationUnitAddressStreet": {
                    "type": "string"
                  },
                  "OrganizationUnitEmail": {
                    "type": "string"
                  },
                  "OrganizationUnitTelephone2": {
                    "type": "string"
                  },
                  "OrganizationUnitTelephone1": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "example-1": {
                  "value": {
                    "OrganizationUnitTelephone1": "777 777 777",
                    "OrganizationUnitTelephone2": "999 999 999",
                    "OrganizationUnitEmail": "info@spu.cz",
                    "OrganizationUnitAddressStreet": "Husinecka",
                    "OrganizationUnitAddressStreetNumber": "1024/11a",
                    "OrganizationUnitAddressCity": "Praha 3",
                    "OrganizationUnitAddressPSC": "13000"
                  }
                }
              }
            }
          }
        },
        "description": "Set properties of OrganizationUnit defined by Organization Unit code"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "OrganizationUnitCode",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "OrganizationUnit": {
        "title": "OrganizationUnitModel",
        "type": "object",
        "x-examples": {
          "OrganizationUnitExample": {
            "OrganizationUnitName": "Úsek ústředního ředitele",
            "OrganizationUnitType": "0c",
            "OrganizationUnitCode": "100000",
            "OrganizationUnitParentCode": "000001",
            "OrganizationUnitShortCut": "UUR",
            "OrganizationUnitDirector": "jana.krejci@spu.cz",
            "OrganizationUnitDeputyDirector": "jana.krejci@spu.cz",
            "OrganizationUnitNetworkAdministrator": "jana.krejci@spu.cz",
            "OrganizationUnitNetworkDeputyAdministrator": "jana.krejci@spu.cz",
            "OrganizationUnitMembers": [
              "jana.krejci@spu.cz",
              "martin.cuchran@spu.cz"
            ],
            "OrganizationUnitSponsors": [
              "jana.krejci@spu.cz",
              "martin.cuchran@spu.cz"
            ],
            "OrganizationUnitAssistants": [
              "jana.krejci@spu.cz",
              "martin.cuchran@spu.cz"
            ],
            "OrganizationUnitTelephone1": "777 777 777",
            "OrganizationUnitTelephone2": "999 999 999",
            "OrganizationUnitEmail": "info@spu.cz",
            "OrganizationUnitAddressStreet": "Husinecka",
            "OrganizationUnitAddressStreetNumber": "1024/11a",
            "OrganizationUnitAddressCity": "Praha 3",
            "OrganizationUnitAddressPSC": "13000"
          }
        },
        "properties": {
          "OrganizationUnitName": {
            "type": "string"
          },
          "OrganizationUnitType": {
            "type": "string"
          },
          "OrganizationUnitCode": {
            "type": "string"
          },
          "OrganizationUnitParentCode": {
            "type": "string"
          },
          "OrganizationUnitShortCut": {
            "type": "string"
          },
          "OrganizationUnitDirector": {
            "type": "string"
          },
          "OrganizationUnitDeputyDirector": {
            "type": "string"
          },
          "OrganizationUnitNetworkAdministrator": {
            "type": "string"
          },
          "OrganizationUnitNetworkDeputyAdministrator": {
            "type": "string"
          },
          "OrganizationUnitMembers": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "OrganizationUnitSponsors": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "OrganizationUnitAssistants": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "OrganizationUnitTelephone1": {
            "type": "string"
          },
          "OrganizationUnitTelephone2": {
            "type": "string"
          },
          "OrganizationUnitEmail": {
            "type": "string"
          },
          "OrganizationUnitAddressStreet": {
            "type": "string"
          },
          "OrganizationUnitAddressStreetNumber": {
            "type": "string"
          },
          "OrganizationUnitAddressCity": {
            "type": "string"
          },
          "OrganizationUnitAddressPSC": {
            "type": "string"
          }
        },
        "required": [
          "OrganizationUnitName",
          "OrganizationUnitCode",
          "OrganizationUnitShortCut"
        ],
        "description": ""
      }
    },
    "securitySchemes": {}
  }
}